server:
  port: 9527
spring:
  application:
    name: ares-zuul
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7777.com:7777/eureka,http://eureka8888.com:8888/eureka,http://eureka9999.com:9999/eureka
  instance:
    instance-id: ares-zuul.com
    prefer-ip-address: true
#zuull网关
zuul:
  prefix: /ares                       #设置统一的公共访问前缀
  ignored-services: "*"               #将所有微服务的原始访问路径关闭,只能通过路由访问
  routes:
    ares-provider:                    #提供者
      path: /department/**            #配置请求URL的请求规则
      serviceId: ares-provider        #指定Eureka注册中心中的服务id